#!/bin/bash
my_array=("apple tea" "banana" "Fruit Basket" "orange")
for ELEMENT in ${my_array[@]}
do
echo File: $ELEMENT.
done
echo ${#my_array}
echo ${my_array[*]}
my_array[2]="abricot" 
echo ${#my_array}
echo ${my_array[*]}
i=0
for ELEMENT in ${my_array[@]}
do
echo "Data ${my_array[$i]} : $ELEMENT."
i=$((i+1))
done
