#!/bin/bash
function function_B {
  echo "Function B."
}
function function_A {
  echo "$1"
}
function adder {
  echo "$(($1 + $2))"
}

# FUNCTION CALLS
# Pass parameter to function A
function_A "Function A."     # Function A.
function_B                   # Function B.
# Pass two parameters to function adder
adder 12 56                  # 68


# enter your function code here
function ENGLISH_CALC {
	if [[ "$2" == "plus" ]]; then
		echo " $1 + $3 = $(($1 + $3))"
	elif [[ "$2" == "minus" ]]; then
		echo " $1 - $3 = $(($1 - $3))"
	elif [[ "$2" == "times" ]]; then
		echo " $1 x $3 = $(($1 * $3))"
	else
		echo erreur dans la saisie
	fi
}
# testing code
ENGLISH_CALC 3 plus 5
ENGLISH_CALC 5 minus 1
ENGLISH_CALC 4 times 6
ENGLISH_CALC 4 ties 6
