#!/bin/bash
#       1234567890123456
STRING="this is a string"
echo ${#STRING}            # 16
SUBSTRING="hat"
expr index "$STRING" "$SUBSTRING"     # 1 is the position of the first 't' in $STRING
POS=1
LEN=3
echo ${STRING:$POS:$LEN}   # his
echo ${STRING:1}           # $STRING contents without leading character
echo ${STRING:12}          # ring
# Code to extract the First name from the data record
DATARECORD="last=Clifford,first=Johnny Boy,state=CA"
COMMA1=`expr index "$DATARECORD" ','`  # 14 position of first comma
CHOP1FIELD=${DATARECORD:$COMMA1}       #
COMMA2=`expr index "$CHOP1FIELD" ','`
LENGTH=`expr $COMMA2 - 6 - 1`
FIRSTNAME=${CHOP1FIELD:6:$LENGTH}      # Johnny Boy
echo $FIRSTNAME
STRING="to be or not to be"
echo ${STRING[@]/be/eat}        # to eat or not to be
echo ${STRING[@]//be/eat}        # to eat or not to eat
echo ${STRING[@]// not/}        # to be or to be
echo ${STRING[@]/#to be/eat now}    # eat now or not to be
echo ${STRING[@]/%be/eat}        # to be or not to eat
echo ${STRING[@]/%be/be on $(date +%Y-%m-%d)}    # to be or not to be on 2012-06-14
#Change1: replace the first occurrence of 'snow' with 'foot'
#Change2: delete the second occurrence of 'snow'
#Change3: replace 'finding' with 'getting'
#Change4: delete all characters following 'wet'
#Tip: One way to implement Change4, if to find the index of 'w' in the word 'wet' and then use substring extraction
BUFFETT="Life is like a snowball. The important thing is finding wet snow and a really long hill."
# write your code here
ISAY="$BUFFETT"
echo $ISAY
ISAY=${ISAY[@]/snow/foot}
ISAY=${ISAY[@]/snow/ }
ISAY=${ISAY[@]/finding/getting}
ISAY=${ISAY[@]/wet*/wet}
echo $ISAY
