#!/bin/bash
PRICE_PER_APPLE=5
MyFirstLetters=ABC
greeting='Hello        world!'
echo "The price of an Apple today is: \$PRICE_PER_APPLE"
echo "The first 10 letters in the alphabet are: ${MyFirstLetters}DEFGHIJ"
echo $greeting" now with spaces: $greeting"

FILELIST=`ls -l`
echo "le contenu du dossier est : $FILELIST"
echo "$FILELIST" > $(pwd)/list_$(/bin/date +%Y-%m-%d).txt
