#!/bin/bash
PRICE_PER_APPLE=5
MyFirstLetters=ABC
greeting='Hello        world!'
echo "The price of an Apple today is: \$PRICE_PER_APPLE"
echo "The first 10 letters in the alphabet are: ${MyFirstLetters}DEFGHIJ"
echo $greeting" now with spaces: $greeting"

FILELIST=`ls -l`
echo "le contenu du dossier est : $FILELIST"
echo "$FILELIST" > $(pwd)/list_$(/bin/date +%Y-%m-%d).txt

date -d "$date1" +%A 
echo $date1

BIRTHDATE="Jan 1, 2000"
Presents=10
BIRTHDAY=$(date -d "$BIRTHDATE" +%A)


# Testing code - do not change it

if [ "$BIRTHDATE" == "Jan 1, 2000" ] ; then
    echo "BIRTHDATE is correct, it is $BIRTHDATE"
else
    echo "BIRTHDATE is incorrect - please retry"
fi
if [ $Presents == 10 ] ; then
    echo "I have received $Presents presents"
else
    echo "Presents is incorrect - please retry"
fi
if [ "$BIRTHDAY" == "Saturday" ] ; then
    echo "I was born on a $BIRTHDAY"
else
    echo "BIRTHDAY is incorrect - please retry"
fi
